In [ ]:
from sklearn.datasets import make_classification
import pandas as pd

X,y=make_classification(n_samples=10,n_features=4,n_classes=2)
import numpy as np
def kfold_indices(data, k):
    fold_size = len(data) // k
    indices = np.arange(len(data))
    folds = []
    for i in range(k):
        test_indices = indices[i * fold_size: (i + 1) * fold_size]
        train_indices = np.concatenate([indices[:i * fold_size], indices[(i + 1) * fold_size:]])
        folds.append((train_indices, test_indices))
    return folds

# Define the number of folds (K)
k = 5

# Get the fold indices
fold_indices = kfold_indices(X, k)

from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier  # import ML  model

# Initialize the machine learning model
model = DecisionTreeClassifier()

# Initialize a list to store the evaluation scores
scores = []

# Iterate through each fold
for train_indices, test_indices in fold_indices:
    X_train, y_train = X[train_indices], y[train_indices]
    X_test, y_test = X[test_indices], y[test_indices]

    print('X_train samples')
    print(X_train)
    print('X_test samples')
    print(X_test)
    # Train the model on the training data
    model.fit(X_train, y_train)

    # Make predictions on the test data
    y_pred = model.predict(X_test)

    # Calculate the accuracy score for this fold
    fold_score = accuracy_score(y_test, y_pred)

    # Append the fold score to the list of scores
    scores.append(fold_score)

# Calculate the mean accuracy across all folds
mean_accuracy = np.mean(scores)
print("K-Fold Cross-Validation Scores:", scores)
print("Mean Accuracy:", mean_accuracy)

X_train samples
[[-1.41810351 -1.61973478  0.90591302 -0.62713814]
 [ 0.88005485  1.64199317  0.66037778  1.5521996 ]
 [-0.04873828  0.2189432   0.55834617  0.47996982]
 [ 0.57367728  0.98399786  0.26467834  0.85410439]
 [-0.05713882  1.23441172  2.53167603  2.34833247]
 [-0.64618041 -0.72604409  0.43585552 -0.26382622]
 [ 0.42708592  0.55098804 -0.15154014  0.30425452]
 [ 0.94754012  0.79553272 -1.15578917 -0.10462271]]
X_test samples
[[-0.12619439 -0.95520737 -1.47651387 -1.53706871]
 [-0.18707515 -0.32959613 -0.10304482 -0.29444029]]
X_train samples
[[-0.12619439 -0.95520737 -1.47651387 -1.53706871]
 [-0.18707515 -0.32959613 -0.10304482 -0.29444029]
 [-0.04873828  0.2189432   0.55834617  0.47996982]
 [ 0.57367728  0.98399786  0.26467834  0.85410439]
 [-0.05713882  1.23441172  2.53167603  2.34833247]
 [-0.64618041 -0.72604409  0.43585552 -0.26382622]
 [ 0.42708592  0.55098804 -0.15154014  0.30425452]
 [ 0.94754012  0.79553272 -1.15578917 -0.10462271]]
X_test samples
[[-1.41810351 -1.

Assignment 3-1&2

In [ ]:
from sklearn.datasets import make_classification
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier

# Generate synthetic data
X, y = make_classification(n_samples=20, n_features=4, n_classes=2)

# Function to get K-fold indices
def kfold_indices(data, k):
    fold_size = len(data) // k
    indices = np.arange(len(data))
    folds = []
    for i in range(k):
        test_indices = indices[i * fold_size: (i + 1) * fold_size]
        train_indices = np.concatenate([indices[:i * fold_size], indices[(i + 1) * fold_size:]])
        folds.append((train_indices, test_indices))
    return folds

# 1) Perform K-Fold Cross-validation with number of samples = 20 and number of splits = 5.
k_1 = 5
fold_indices_1 = kfold_indices(X, k_1)
model_1 = DecisionTreeClassifier()
scores_1 = []

for train_indices, test_indices in fold_indices_1:
    X_train, y_train = X[train_indices], y[train_indices]
    X_test, y_test = X[test_indices], y[test_indices]
    model_1.fit(X_train, y_train)
    y_pred = model_1.predict(X_test)
    fold_score = accuracy_score(y_test, y_pred)
    scores_1.append(fold_score)

mean_accuracy_1 = np.mean(scores_1)
print("K-Fold Cross-Validation Scores (K=5):", scores_1)
print("Mean Accuracy (K=5):", mean_accuracy_1)

# 2) Perform K-Fold Cross-validation with number of samples = 20 and number of splits = 10.
k_2 = 10
fold_indices_2 = kfold_indices(X, k_2)
model_2 = DecisionTreeClassifier()
scores_2 = []

for train_indices, test_indices in fold_indices_2:
    X_train, y_train = X[train_indices], y[train_indices]
    X_test, y_test = X[test_indices], y[test_indices]
    model_2.fit(X_train, y_train)
    y_pred = model_2.predict(X_test)
    fold_score = accuracy_score(y_test, y_pred)
    scores_2.append(fold_score)

mean_accuracy_2 = np.mean(scores_2)
print("\nK-Fold Cross-Validation Scores (K=10):", scores_2)
print("Mean Accuracy (K=10):", mean_accuracy_2)

K-Fold Cross-Validation Scores (K=5): [1.0, 1.0, 1.0, 0.75, 0.5]
Mean Accuracy (K=5): 0.85

K-Fold Cross-Validation Scores (K=10): [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.5, 0.5, 0.5]
Mean Accuracy (K=10): 0.85


Assignment 3-3

In [ ]:
# Compare mean accuracy of the two cases
print("\nMean Accuracy (K=5):", mean_accuracy_1)
print("Mean Accuracy (K=10):", mean_accuracy_2)

# Inference
if mean_accuracy_1 > mean_accuracy_2:
    print("Inference: K-Fold Cross-Validation with K=5 has a higher mean accuracy.")
elif mean_accuracy_1 < mean_accuracy_2:
    print("Inference: K-Fold Cross-Validation with K=10 has a higher mean accuracy.")
else:
    print("Inference: Both cases have the same mean accuracy.")



Mean Accuracy (K=5): 0.85
Mean Accuracy (K=10): 0.85
Inference: Both cases have the same mean accuracy.
